### ISSUE TITLE
pass maintainership to new elite team

### ISSUE THREAD

**Issue by willkg** [mozilla/dennis#120]
No one chimed in on the discussion topic and I don't use Dennis anymore and I've got too many things on my plate.

I looked through the projects that are using it and wrote up these issues:

* addons-server: https://github.com/mozilla/addons-server/issues/19075
* kitsune: https://github.com/mozilla/kitsune/issues/5086
* vouched-mozillians: https://github.com/mozilla/vouched-mozillians/issues/51
* kuma: https://github.com/mdn/kuma/issues/8063

If no one steps in to take over by May 2022, I'll end Dennis.

**Comment by diox** [comment]
The AMO team needs dennis, even if we are not planning to implement any new features (if anything we'd _remove_ some). 

Given the lack of activity in the other issues you filed, I guess this falls on us... Could you transfer the repos to `mozilla` org and give me admin rights on the repo and on pypi (I'm https://pypi.org/user/diox/) so that I sort things out ?

**Comment by willkg** [comment]
I talked to @akatsoulas (kitsune) and he still needs it, too.

I'll do the following:

1. clean up PRs, issues, and docs as best I can and depending on how involved that is, I might end up doing one last release
2. transfer it to the mozilla github org
3. get @diox and @akatsoulas admin rights to dennis in github, readthedocs, and pypi
4. have a celebratory beer or something--I really liked working on dennis and there's some really amazing things in here and it'll be sad to pass it along

**Comment by willkg** [comment]
I went through all the clean up I want to do. I transferred it to the mozilla org. I'm waiting to get admin access again and then I'll continue with steps.

**Comment by willkg** [comment]
@diox @akatsoulas : What are your readthedocs usernames? And what are your PyPI usernames?

**Comment by diox** [comment]
I'm also `diox` on both readthedocs and PyPI.

**Comment by willkg** [comment]
1. I did a 1.0.0 release: https://pypi.org/project/dennis/
2. I fixed readthedocs building and added @diox .
3. I invited @diox as an owner of Dennis on PyPI.

I think I'm all set here. Is there anything else you want me to do?

**Comment by diox** [comment]
Should be good to go, thanks @willkg !

**Comment by willkg** [comment]
Awesome! Thank you for taking the maintenance burden on!

**Comment by akatsoulas** [comment]
Hi apologies for missing this. I am `akatsoulas` on both PyPI and readthedocs. Thanks!

**Comment by diox** [comment]
Invite sent!
