### ISSUE TITLE
dennis can't handle double {{ }}

### ISSUE THREAD

**Issue by eviljeff** [mozilla/dennis#134]
According to the python format syntax, literal brace characters (i.e. you want a literal `{` or `}` in your end string) are represented as `{{` or `}}` https://docs.python.org/3/library/string.html#format-string-syntax - the dennis linter raises [error E103](https://github.com/mozilla/dennis/blob/main/dennis/linter.py#L185) instead.  (E102, the right hand missing brace error, isn't raised though - but maybe it's suppressed by E103 being raised?)

**Comment by eviljeff** [comment]
I'm assuming the fix is to adjust the [regex r"(?:\{[^\}]+(?:\{|$))"](https://github.com/mozilla/dennis/blob/main/dennis/linter.py#L160)

**Comment by willkg** [comment]
With these sorts of bugs, the best thing to provide is the string you're having problems with. Generally, I provide the entry in the PO file.

**Comment by eviljeff** [comment]
It can be reproduced in a python shell with `re.compile(r'(?:(?:^|\})[^\{]*\})').findall('I want literal {{braces}}.')  - https://github.com/mozilla/addons-server/blob/5aebf5b7cde2fdf224109efe5b6c78c1d25432ba/locale/en_US/LC_MESSAGES/django.po#L507 is the .po file that's failing,

**Comment by willkg** [comment]
```
msgid "You must provide an object of {{lang-code:value}}."
msgstr "You must provide an object of {{lang-code:value}}."
```

**Comment by eviljeff** [comment]
After observing that E102 didn't fail with double braces we spent some time on the idea that we could reuse the regex for E102 with a reversed string (and swapped `{` and `}`).  

Unfortunately it appears the regex for E102 doesn't catch a broken string such as `'msgstr "{q} | {{product} foo bar"\n'` (there is an explicit test for this case in the [test class for E103](https://github.com/mozilla/dennis/blob/main/tests/test_linter.py#L301:L336), but not in the [tests for E102](https://github.com/mozilla/dennis/blob/main/tests/test_linter.py#L234:L259)).

So we're back to having to fix the E103 regex directly, or otherwise workaround it.  Should I log a new issue for the E102 deficiency?
